limit_req_zone $binary_remote_addr zone=login_limit:10m rate=5r/m;

server {
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate     /etc/nginx/certs/cert.pem;
    ssl_certificate_key /etc/nginx/certs/key.pem;

    location /api/auth/ {
        limit_req zone=login_limit burst=5 nodelay;
        proxy_pass http://auth-service:3001;
    }
    location /api/tasks/ {
        proxy_pass http://task-service:3002;
    }
    location /api/logs/ {
        proxy_pass http://log-service:3003;
    }
    location / {
        proxy_pass http://frontend:80;
    }
}